// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Author struct {
	ID   int32
	Name string
	Bio  sql.NullString
}

type User struct {
	ID        int32
	Name      string
	Email     sql.NullString
	CreatedAt sql.NullInt32
}
